language: c
compiler:
  - clang
  - gcc
before_install:
  - sudo apt-get install help2man valgrind gperf lcov gettext autopoint 
  - which automake
  - automake --version
  - which autoconf
  - autoconf --version
  - which autopoint
  - autopoint --version
  - which gettext
  - gettext --version
  - which autoreconf
  - autoreconf --version
script:
- "( git fetch --unshallow ; true )"
- ls -l
- ./bootstrap
- git describe --always
- ./build-aux/git-version-gen .tarball-version
- ./configure
- make
- make check VERBOSE=yes
- cat tests/*.log ; true
- cat ./test-suite.log ; true
- make dist
